### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ghost** [ShubhankarRawat/Airplane-Detection-for-Satellites#1]
I am getting the errors -

It would be great help if you please help me !

[Errno 2] No such file or directory: 'G:/HURAProject/production/planerecognition/training/train\\VOC2007\\ImageSets\\Main\\trainval.txt'
[Errno 2] No such file or directory: 'G:/HURAProject/production/planerecognition/training/train\\VOC2007\\ImageSets\\Main\\test.txt'

Traceback (most recent call last):
  File "C:/Users/nitur/PycharmProjects/Airplane-Detection-for-Satellites-master/train_frcnn.py", line 87, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "C:\Users\nitur\PycharmProjects\Airplane-Detection-for-Satellites-master\keras_frcnn\pascal_voc_parser.py", line 46, in get_data
    annots = [os.path.join(annot_path, s) for s in os.listdir(annot_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:/HURAProject/production/planerecognition/training/train\\VOC2007\\Annotations'

Process finished with exit code 1

**Comment by ShubhankarRawat** [comment]
It seems the code can not read the path you specified, try re-verifying it
