### ISSUE TITLE
traning isuue

### ISSUE THREAD

**Issue by Onkarsus13** [ShubhankarRawat/Airplane-Detection-for-Satellites#2]
Using TensorFlow backend.
Parsing annotation files
Traceback (most recent call last):
  File "train_frcnn.py", line 79, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "/content/drive/My Drive/Airplane-Detection-for-Satellites-master/keras_frcnn/simple_parser.py", line 37, in get_data
    (rows,cols,_) = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by ShubhankarRawat** [comment]
Sorry for the late reply, it seems the code is not reading the images. Try verifying the path to the images

**Comment by Onkarsus13** [comment]
I have tryed it

**Comment by Onkarsus13** [comment]
If possible can u try the code at ur end pre chevk weather it's reading the images or not
